# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: frontend
#   namespace : roboshop
#   labels:
#     component: frontend
#     project: roboshop
#     tier: web
# data:
#  MONGO: "true" 
#  MONGO_URL: "mongodb://mongodb:27017/frontend"
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace : roboshop
  # deployment labels
  labels:
    component: frontend
    project: roboshop
    tier: web
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: frontend
      project: roboshop
      tier: web
  # This is pod definition
  template:
    metadata:
      labels:
        component: frontend
        project: roboshop
        tier: web
    spec:
      containers:
      - name: frontend
        image: sreevallik/frontend:v1
        # envFrom:
        # - configMapRef:
        #     name: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace : roboshop
  labels:
    component: frontend
    project: roboshop
    tier: web
spec:
  type: LoadBalancer
  selector:
    component: frontend
    project: roboshop
    tier: web
  ports:
    - protocol: http
      port: 80 # service port
      targetPort: 80 # container port        